services:
  - type: web
    name: creativestationary
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./db/custom.db
      - key: PORT
        fromService:
          type: web
          name: creativestationary
          property: port

