services:
  - type: web
    name: creativestationary
    env: node
    plan: starter
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/data/custom.db
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        fromService:
          type: web
          name: creativestationary
          property: port

